common/src/main/java/com/hartwig/actin/clinical/serialization/ClinicalRecordJson.java, common/src/test/resources/clinical/patient.clinical.json
@kduyvesteyn I'm not sure if this is exactly what you were looking for as a deserialization improvement, but it works using types without explicitly extracting each field. I left it out of the feature branch for now but I'll merge to that branch if you'd like to include it.
=> Replace explicit JSON deserialization with type adapters

report/src/main/java/com/hartwig/actin/report/pdf/tables/molecular/MolecularDriversGenerator.java
Explicitly check variants for reportability and potential for subclonal
to avoid false positives.
This PR follows from discussion in #1.
=> ACTIN-11: Add footnote for reportable, potentially subclonal variants

report/src/main/java/com/hartwig/actin/report/interpretation/EvaluatedTrialComparator.java, report/src/main/java/com/hartwig/actin/report/interpretation/EvaluatedTrialFactory.java, report/src/main/java/com/hartwig/actin/report/pdf/tables/treatment/EligibleActinTrialsGenerator.java, report/src/main/java/com/hartwig/actin/report/pdf/util/Cells.java, report/src/test/java/com/hartwig/actin/report/interpretation/EvaluatedTrialComparatorTest.java
Refactor EvaluatedTrialFactory to make use of streams
=> ACTIN-20: Show cohorts without slots at bottom of table in grey

algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/HasSufficientTumorMutationalBurden.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/HasTumorMutationalLoadWithinRange.kt
See https://hartwigmedical.atlassian.net/browse/ACTIN-1751?atlOrigin=eyJpIjoiOTM0NDQyYjg2YmQ4NDcxNGI4NDlmYzk1NzRiNzQ3YmIiLCJwIjoiaiJ9
=> ACTIN-1751: Improve TMB and TML messages

datamodel/src/test/kotlin/com/hartwig/actin/datamodel/molecular/TestMolecularFactory.kt, report/src/main/kotlin/com/hartwig/actin/report/pdf/ReportContentProvider.kt, report/src/main/kotlin/com/hartwig/actin/report/pdf/tables/trial/EligibleApprovedTreatmentGenerator.kt, report/src/test/kotlin/com/hartwig/actin/report/pdf/tables/trial/EligibleApprovedTreatmentGeneratorTest.kt
Fill 'approved treatments considered eligible' properly in case of colorectal cancer trial matching report
It currently only displays the treatment name.
=> ACTIN-1678: Fill 'approved treatments considered eligible' properly for CRC patients

common/src/main/kotlin/com/hartwig/actin/TreatmentDatabase.kt, datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/LabMeasurement.kt
Confirmed by Jesse that what we talked about in slack is indeed elastase in faeces. 
Also included a small bug fix for my PR from yesterday (searching the drug by lowercase) I noticed in the clinical curation today
=> ACTIN-1793: Add new LabMeasurement for elastase

report/src/main/kotlin/com/hartwig/actin/report/interpretation/TumorOriginInterpreter.kt, report/src/main/kotlin/com/hartwig/actin/report/pdf/tables/molecular/PredictedTumorOriginGenerator.kt, report/src/main/kotlin/com/hartwig/actin/report/pdf/tables/molecular/WGSSummaryGeneratorFunctions.kt, report/src/main/kotlin/com/hartwig/actin/report/pdf/tables/trial/EligibleApprovedTreatmentGenerator.kt, report/src/test/kotlin/com/hartwig/actin/report/interpretation/TumorOriginInterpreterTest.kt
I have verified that for ACTN01020436 this leads to desired change
If either of you could review that would be appreciated! (both is overkill I think)
=> ACTIN-1797: Do not show SOC options based on CUPPA result of insufficient quality WGS sample

datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/LabUnit.kt
Needed for EMC clinical ingestion
=> ACTIN-1810: Add labunit mg/g

clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/emc/vitalfunction/VitalFunctionEntry.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/emc/vitalfunction/VitalFunctionExtraction.kt, clinical/src/test/kotlin/com/hartwig/actin/clinical/feed/emc/vitalfunction/VitalFunctionFeedValidatorTest.kt
Same we had few weeks ago. Also clarified the warning
=> ACTIN-1826: Add NIBP ST no and clarify warning

clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/standard/extraction/StandardPriorIHCTestExtractor.kt, clinical/src/test/kotlin/com/hartwig/actin/clinical/feed/standard/extraction/StandardPriorIHCTestExtractorTest.kt
Alternative to https://github.com/hartwigmedical/actin/pull/1048
Use an empty extraction evaluation when combining the free text curation with the others.
=> ACTIN-1817 Ignore curation warnings from free text for IHC

common/src/main/kotlin/com/hartwig/actin/medication/MedicationCategories.kt
Needed for curation HAS_RECEIVED_ANY_ANTI_CANCER_THERAPY_EXCL_CATEGORIES_X_WITHIN_Y_WEEKS[L01EB, 2]
=> ACTIN-1849: Add L01EB

clinical/src/main/kotlin/com/hartwig/actin/clinical/ClinicalIngestionApplication.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/ClinicalIngestionConfig.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/standard/DataQualityMask.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/standard/StandardDataIngestion.kt, clinical/src/test/kotlin/com/hartwig/actin/clinical/feed/standard/DataQualityMaskTest.kt, clinical/src/test/kotlin/com/hartwig/actin/clinical/feed/standard/StandardDataIngestionTest.kt, common/src/main/kotlin/com/hartwig/actin/configuration/EnvironmentConfiguration.kt, datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/provided/ProvidedClinicalDatamodel.kt
POC = Prior Other Conditions. Use the config yaml to turn this feature on and off and implemented in the data quality mask.
=> ACTIN-1860: Add optional scrubber for data likely to be in POC

algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/general/HasMaximumWHOStatus.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/general/HasMinimumLanskyKarnofskyScore.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/general/HasWHOStatus.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/GeneHasSufficientCopyNumber.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/HasSpecificHLAType.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/HasUGT1A1Haplotype.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/treatment/CurrentlyGetsChemoradiotherapyWithSpecificChemotherapyTypeAndMinimumCycles.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/tumor/HasTumorStage.kt
See jira ticket, also removed "requested" in message in some other places to avoid confusing messages if NOT(..) is used.
=> ACTIN-1880: Clarify messages

report/src/main/kotlin/com/hartwig/actin/report/pdf/chapters/MolecularDetailsChapter.kt
I don't know why we had it in the first place.
=> ACTIN-1955: Drop unneeded sentence

algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/toxicity/ToxicityFunctions.kt, algo/src/test/kotlin/com/hartwig/actin/algo/evaluation/toxicity/ToxicityFunctionsTest.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/standard/extraction/StandardOncologicalHistoryExtractor.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/standard/extraction/StandardPriorPrimariesExtractor.kt, common/src/main/kotlin/com/hartwig/actin/clinical/sort/SurgeryDescendingDateComparator.kt, common/src/test/kotlin/com/hartwig/actin/clinical/sort/SurgeryDescendingDateComparatorTest.kt, datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/Surgery.kt, datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/Toxicity.kt, pom.xml, report/src/main/kotlin/com/hartwig/actin/report/pdf/tables/clinical/PatientCurrentDetailsGenerator.kt
Adjust to feed DateEntry start date being nullable, makingToxicity.evaluatedDate and Surgery.endDate nullable as well.
=> ACTIN-1993 Adjust to feed DateEntry start date being nullable 

datamodel/src/main/kotlin/com/hartwig/actin/datamodel/clinical/treatment/DrugType.kt
Will also update drug.json after merge
=> ACTIN-2048: Add NECTIN_4_ANTIBODY

clinical/src/test/resources/curation/non_oncological_history.tsv, clinical/src/test/resources/feed/standard/output/ACTN01029999.clinical.json
I also deleted the corresponding column from the curation spreadsheets.
=> ACTIN-2044: Remove all references to isContraindicationForTherapy

clinical/src/main/kotlin/com/hartwig/actin/clinical/ClinicalIngestionFeedAdapter.kt, clinical/src/main/kotlin/com/hartwig/actin/clinical/feed/emc/EmcClinicalFeedIngestion.kt
Add logging for curation messages
=> ACTIN-2145: Drop redundant empty questionnaire warnings

algo/src/main/kotlin/com/hartwig/actin/algo/TreatmentMatcher.kt, algo/src/main/kotlin/com/hartwig/actin/algo/matchcomparison/MatchOutputComparisonApplication.kt, algo/src/test/kotlin/com/hartwig/actin/algo/TreatmentMatcherTest.kt, common/src/test/kotlin/com/hartwig/actin/algo/serialization/TreatmentMatchJsonTest.kt, common/src/test/resources/algo/patient.treatment_match.json, database/src/main/kotlin/com/hartwig/actin/database/dao/TreatmentMatchDAO.kt, database/src/main/resources/generate_database.sql, datamodel/src/main/kotlin/com/hartwig/actin/datamodel/algo/TreatmentMatch.kt, datamodel/src/test/kotlin/com/hartwig/actin/datamodel/algo/TestTreatmentMatchFactory.kt, report/src/main/kotlin/com/hartwig/actin/report/TabularTreatmentMatchWriter.kt, system/src/test/resources/example_treatment_match/EXAMPLE-LUNG-01.treatment_match.json
Property doesn't make sense anymore on the level of treatment match
=> ACTIN-2212: Remove sampleId from treatment match

molecular/src/main/kotlin/com/hartwig/actin/molecular/orange/DriverEventFactory.kt, molecular/src/test/kotlin/com/hartwig/actin/molecular/orange/DriverEventFactoryTest.kt, report/src/main/kotlin/com/hartwig/actin/report/interpretation/MolecularDriverEntryFactory.kt, report/src/test/kotlin/com/hartwig/actin/report/interpretation/MolecularDriverEntryFactoryTest.kt
For a gene with 6 letters, it fits exactly in the column :)
=> ACTIN-2252: Improve display of partial amplifications

molecular/src/main/kotlin/com/hartwig/actin/molecular/panel/PanelVariantAnnotator.kt, molecular/src/test/kotlin/com/hartwig/actin/molecular/panel/PanelVariantAnnotatorTest.kt
=> ACTIN-2284: exception instead of logging error when transvar fails

algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/GeneIsWildType.kt, algo/src/main/kotlin/com/hartwig/actin/algo/evaluation/molecular/MolecularEvaluationFunction.kt, algo/src/test/kotlin/com/hartwig/actin/algo/evaluation/molecular/GeneIsWildTypeTest.kt
Was not getting used.  Add simple test for now, will add more comprehensive unit testing later.
=> ACTIN-2305: Pass custom precedence into combine function

common/src/main/kotlin/com/hartwig/actin/TreatmentDatabase.kt, common/src/test/kotlin/com/hartwig/actin/TreatmentDatabaseTest.kt
Needed for populating a list of treatments in the feed review tool.
=> ACTIN-2390: Return drug and treatment listings from database

molecular/src/test/kotlin/com/hartwig/actin/molecular/panel/PanelTestConstants.kt, molecular/src/test/kotlin/com/hartwig/actin/molecular/panel/TestPanelConstants.kt
- Removed unused function from PanelTestConstants.kt
- Relocated constants from `TestPanel'
=> Rohans first HMF Ticket!:) Code cleanup
